<a href="https://colab.research.google.com/github/nidheesh-p/AI-Learning/blob/master/4_Introduction__to_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to NumPy
NumPy is a powerful library for numerical computing in Python. It provides support for arrays, matrices, and many mathematical functions to operate on these data structures.

## Importing NumPy
To use NumPy, you first need to import it. The convention is to import NumPy using the alias `np`.

In [1]:
# Importing NumPy
import numpy as np


In [9]:
arr = np.array([1, 2, 3, 4])
print(arr)
print(np.average(arr))
print(arr.std())
print(arr.mean())

[1 2 3 4]
2.5
1.118033988749895
2.5


## Essential NumPy Functions
Here are some essential NumPy functions that you will commonly use:

In [10]:
# Creating an array
arr = np.array([1, 2, 3, 4])
print(f'Array: {arr}')

# Creating an array with a range of values
arr_range = np.arange(10)
print(f'Array with range: {arr_range}')

# Creating an array of zeros
arr_zeros = np.zeros((3, 3))
print(f'Array of zeros:\n{arr_zeros}')

# Creating an array of ones
arr_ones = np.ones((2, 2))
print(f'Array of ones:\n{arr_ones}')

# Reshaping an array
arr_reshaped = arr_range.reshape((2, 5))
print(f'Reshaped array:\n{arr_reshaped}')

# Getting the shape of an array
print(f'Shape of the array: {arr_reshaped.shape}')

# Basic arithmetic operations
arr_sum = arr + 2
print(f'Array after addition: {arr_sum}')
arr_mul = arr * 3
print(f'Array after multiplication: {arr_mul}')

# Element-wise operations
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
arr_add = arr1 + arr2
print(f'Element-wise addition: {arr_add}')
arr_mul = arr1 * arr2
print(f'Element-wise multiplication: {arr_mul}')

Array: [1 2 3 4]
Array with range: [0 1 2 3 4 5 6 7 8 9]
Array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array of ones:
[[1. 1.]
 [1. 1.]]
Reshaped array:
[[0 1 2 3 4]
 [5 6 7 8 9]]
Shape of the array: (2, 5)
Array after addition: [3 4 5 6]
Array after multiplication: [ 3  6  9 12]
Element-wise addition: [ 6  8 10 12]
Element-wise multiplication: [ 5 12 21 32]


## Adding and Averaging Based on Different Axes
In this section, we will explore how to perform addition and averaging operations along different axes in NumPy arrays.

In [11]:
# Creating two 2D arrays with shape (4, 4)
arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
arr2 = np.array([[16, 15, 14, 13], [12, 11, 10, 9], [8, 7, 6, 5], [4, 3, 2, 1]])
print(f'Array 1:\n{arr1}')
print(f'Array 2:\n{arr2}')

# Adding the arrays
arr_sum = arr1 + arr2
print(f'Sum of arrays:\n{arr_sum}')

# Averaging the arrays along different axes
arr_avg_axis0 = np.mean(arr_sum, axis=0)
print(f'Average along axis 0: {arr_avg_axis0}')

arr_avg_axis1 = np.mean(arr_sum, axis=1)
print(f'Average along axis 1: {arr_avg_axis1}')

Array 1:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Array 2:
[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
Sum of arrays:
[[17 17 17 17]
 [17 17 17 17]
 [17 17 17 17]
 [17 17 17 17]]
Average along axis 0: [17. 17. 17. 17.]
Average along axis 1: [17. 17. 17. 17.]
